spring:
  profiles:
    active: prod, test
  application:
    name: POSReports

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    drop-first: false
